# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-13 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0008_usermeta_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
