# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0009_auto_20170313_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emailtemplatebody',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('A', 'Announcement'), ('L', 'Letter')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='avatar',
            field=models.ImageField(default=None, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='invited_to',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='member_of',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='password_reset_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='requested_to',
            field=models.TextField(default=''),
        ),
    ]
