# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 07:39
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
from slugify import slugify


def update_slugs(apps, schema_editor):
    Organization = apps.get_model('tolmach', 'Organization')

    all_orgs = Organization.objects.all()

    for org in all_orgs:
        org.slug = slugify(org.name)
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0011_auto_20180330_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(update_slugs),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
