# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 08:24
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
from tolmach.utils import random_string

def update_invite_link_codes(apps, schema_editor):
    Organization = apps.get_model('tolmach', 'Organization')

    all_orgs = Organization.objects.all()

    for org in all_orgs:
        org.invite_link_code = random_string(15)
        org.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0012_auto_20180403_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_link_code',
            field=models.CharField(default=None, null=True, unique=True, max_length=15),
        ),
        migrations.RunPython(update_invite_link_codes),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
