# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import tolmach.models


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0013_auto_20180422_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='invite_link_code',
            field=models.CharField(default=tolmach.models.random_invite_code, max_length=15, null=True, unique=True),
        ),
    ]
