# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import tolmach.models


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0014_auto_20180424_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='api_key',
            field=models.CharField(default=tolmach.models.random_string, max_length=256),
        ),
    ]
