# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0015_auto_20180813_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
