# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-10 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0016_usermeta_last_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairstats',
            name='source_lang',
        ),
        migrations.RemoveField(
            model_name='pairstats',
            name='target_lang',
        ),
        migrations.RemoveField(
            model_name='pairstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='PairStats',
        ),
    ]
