# Generated by Django 2.2 on 2021-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0018_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='tm_percentage',
            field=models.IntegerField(default=60),
        ),
    ]
