# Generated by Django 2.2 on 2026-07-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0019_usermeta_tm_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplatebody',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='emailtemplatebody',
            name='template',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='EmailTemplateBody',
        ),
    ]
