# Generated by Django 2.2 on 2026-03-18 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc, now
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0019_usermeta_tm_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='email_appove_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='email_approve_token_request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='email_approved',
            field=models.BooleanField(default=False),
        ),
    ]
