# Generated by Django 2.2 on 2026-08-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0021_auto_20260709_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeta',
            name='email',
        ),
    ]
