# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-06 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def move_pair_stats_from_tolmach_app(apps, schema_editor):
    oldPairStats = apps.get_model('tolmach', 'PairStats')
    newPairStats = apps.get_model('stats', 'PairStats')

    all_old_stats = oldPairStats.objects.all().iterator()

    new_stats_bulk_list = []

    for st in all_old_stats:
        new_st = newPairStats(
            user = st.user,
            fragments_translated = st.fragments_translated,
            source_lang = st.source_lang,
            target_lang = st.target_lang
        )
        new_stats_bulk_list.append(new_st)

    newPairStats.objects.bulk_create(new_stats_bulk_list, 1000)

def parse_entries_to_entries_stats(apps, schema_editor):
    import re
    TextEntry = apps.get_model('translations', 'TextEntry')
    Project = apps.get_model('translations', 'Project')
    EntryStats = apps.get_model('stats', 'EntryStats')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    all_users = User.objects.all()

    # print("parsing users array")
    user_count = 1
    for user in all_users:
        # print("parsing users array:", user_count, "(id = %d)" % user.id)
        pre_dict = {}
        user_entries = TextEntry.objects.only("time_created", "text").filter(id_in_text=0, author=user).iterator()
        for ent in user_entries:
            meta_key = "%s|%d" % (ent.time_created.strftime("%Y%m%d"), ent.text.project.id)
            if not meta_key in pre_dict:
                pre_dict[meta_key] = [1, len(re.sub(r"<hr [rl].*?>", "", ent.body))]
            else:
                pre_dict[meta_key][0] += 1
                pre_dict[meta_key][1] += len(re.sub(r"<hr [rl].*?>", "", ent.body))

        # print("collecting parsed entries to bulk:", user_count)
        new_entry_bulk_list = []
        for key, value in pre_dict.items():
            date = int(key.split("|")[0])
            project_id = int(key.split("|")[1])

            new_ent_stat = EntryStats(
                user=user,
                date=date,
                project=Project.objects.get(id=project_id),
                action_count=value[0],
                characters_count=value[1],
                action_type="add"
            )
            # new_ent_stat.save()
            new_entry_bulk_list.append(new_ent_stat)

        # print("bulk insert entries:", user_count)
        EntryStats.objects.bulk_create(new_entry_bulk_list, 1000)
        user_count += 1


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translations', '0031_textentry_meta_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0005_language_code_tmx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('action_count', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_stats_source_lang', to='entries.Language')),
                ('target_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_stats_target_lang', to='entries.Language')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dict_stats_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('action_type', models.CharField(max_length=15)),
                ('action_count', models.IntegerField(default=0)),
                ('characters_count', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_stats_project', to='translations.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_stats_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PairStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragments_translated', models.IntegerField(default=0)),
                ('source_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_stats_source_lang', to='entries.Language')),
                ('target_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_stats_target_lang', to='entries.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_stats_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(move_pair_stats_from_tolmach_app),
        migrations.RunPython(parse_entries_to_entries_stats),
    ]
