# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-10 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_language_code_tmx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0032_auto_20181010_0603'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dictstats',
            unique_together=set([('user', 'date', 'source_lang', 'target_lang')]),
        ),
        migrations.AlterUniqueTogether(
            name='entrystats',
            unique_together=set([('user', 'date', 'project', 'action_type')]),
        ),
    ]
