# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-10 03:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_language_code_tmx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0002_auto_20181010_0603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pairstats',
            unique_together=set([('user', 'source_lang', 'target_lang')]),
        ),
    ]
