
[program:chtec]
command=python -u /var/www/tolma.ch/chtec/chtec-service.py
user=root
directory=/var/www/tolma.ch/chtec
autostart=true
autorestart=true
stdout_logfile=/var/log/tolma.ch/chtec.out.log
stderr_logfile=/var/log/tolma.ch/chtec.out.log

[program:tolmach-channels-workers]
command=python /var/www/tolma.ch/manage.py runworker
process_name=asgi_worker%(process_num)s
numprocs=4
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/tolma.ch/channels-workers.out.log
stderr_logfile=/var/log/tolma.ch/channels-workers.out.log

[program:tolmach-background-tasks]
command=python /var/www/tolma.ch/manage.py process_tasks
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/tolma.ch/tasks.log
stderr_logfile=/var/log/tolma.ch/tasks.log

[program:tolmach-daphne]
command=daphne -b 0.0.0.0  --websocket_connect_timeout -1  tolmach.asgi:channel_layer
directory=/var/www/tolma.ch/
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/tolma.ch/daphne.out.log
stderr_logfile=/var/log/tolma.ch/daphne.out.log

[program:tolmach-uwsgi]
directory=/var/www/tolma.ch/
command=uwsgi --ini /etc/tolmach.ini
user=root
stopsignal=QUIT
stderr_logfile=/var/log/tolma.ch/uwsgi.log
stdout_logfile=/var/log/tolma.ch/uwsgi.log