[uwsgi]

# Django-related settings
# the base directory (full path)
chdir           = /var/www/tolma.ch
# Django's wsgi file
module          = tolmach.wsgi
# the virtualenv (full path)

# process-related settings
# master
master          = true
# maximum number of worker processes
processes       = 10
pidfile		= /var/www/tolmach.pid
#daemonize	= /var/log/tolma.ch/uwsgi.log
# the socket (use the full path to be safe
socket          = /var/www/tolmach.sock
http-socket     = :7000
# ... with appropriate permissions - may be needed
chmod-socket    = 777
# clear environment on exit
vacuum          = true

ignore-sigpipe  = true
ignore-write-errors = true
disable-write-exception = true
enable-threads = true
buffer-size = 32768

touch-reload    = /var/www/tolma.ch/.reload
log-x-forwarded-for = true

env=DJANGO_SETTINGS_MODULE=tolmach.settings
