# Generated by Django 2.2 on 2021-02-09 14:07

import autoslug.fields
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0006_language_code_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('overview', markdownx.models.MarkdownxField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', markdownx.models.MarkdownxField()),
                ('published', models.BooleanField()),
                ('categories', models.ManyToManyField(blank=True, to='blog.Category')),
                ('language', models.ForeignKey(default=None, on_delete=None, to='entries.Language')),
            ],
        ),
    ]
