# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_language_plural_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
