# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 14:45
from __future__ import unicode_literals

from django.db import migrations, models


def add_base_languages_tmx(apps, schema_editor):
    Language = apps.get_model('entries', 'Language')
    langlist = {'en': 'en-US',
                'ru': 'ru-RU',
                'zh': 'zh-CN',
                'es': 'es-ES',
                'ko': 'ko-KR',
                'ja': 'ja-JP',
                'fr': 'fr-FR',
                'de': 'de-DE',
                'it': 'it-IT'}
    for key, value in langlist.items():
        new_code_lang = Language.objects.get(code=key)
        new_code_lang.code_tmx = value
        new_code_lang.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20180308_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code_tmx',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.RunPython(add_base_languages_tmx),
    ]
