# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models


def add_regional_languages(apps, schema_editor):
    Language = apps.get_model('entries', 'Language')
    all_curr_languages = Language.objects.all()
    for i in all_curr_languages:
        if not i.code == "zh":
            i.code_region = i.code_tmx.replace("-", "_")
        else:
            i.code_region = "zh_Hans_CN"
        i.save()

    langlist = {
        'en_GB':
            {
                'code': 'en',
                'code_tmx': 'en-GB',
                'code_639_3': 'eng',
                'name': 'English (Great Britain)'
            },
        'es_MX':
            {
                'code': 'es',
                'code_tmx': 'es-MX',
                'code_639_3': 'spa',
                'name': 'Spanish (Mexico)'
            },
        'es_CL':
            {
                'code': 'es',
                'code_tmx': 'es-CL',
                'code_639_3': 'spa',
                'name': 'Spanish (Chile)'
            },
        'de_AT':
            {
                'code': 'de',
                'code_tmx': 'de-AT',
                'code_639_3': 'deu',
                'name': 'German (Austria)'
            },
        'de_CH':
            {
                'code': 'de',
                'code_tmx': 'de-CH',
                'code_639_3': 'deu',
                'name': 'German (Switzerland)'
            },
        'fr_CA':
            {
                'code': 'fr',
                'code_tmx': 'fr-CA',
                'code_639_3': 'fra',
                'name': 'French (Canada)'
            },
        'fr_BE':
            {
                'code': 'fr',
                'code_tmx': 'fr-BE',
                'code_639_3': 'fra',
                'name': 'French (Belgium)'
            },
        'fr_CH':
            {
                'code': 'fr',
                'code_tmx': 'fr-CH',
                'code_639_3': 'fra',
                'name': 'French (Switzerland)'
            },
        'it_CH':
            {
                'code': 'it',
                'code_tmx': 'it-CH',
                'code_639_3': 'ita',
                'name': 'Italian (Switzerland)'
            },
        'zh_Hans_SG':
            {
                'code': 'zh',
                'code_tmx': 'zh-SG',
                'code_639_3': 'zho',
                'name': 'Chinese (simplified, Singapore)'
            },
        'zh_Hant_TW':
            {
                'code': 'zh',
                'code_tmx': 'zh-TW',
                'code_639_3': 'zho',
                'name': 'Chinese (traditional, Taiwan)'
            },
        'zh_Hant_HK':
            {
                'code': 'zh',
                'code_tmx': 'zh-HK',
                'code_639_3': 'zho',
                'name': 'Chinese (traditional, Hong Kong SAR)'
            },
        'zh_Hant_MO':
            {
                'code': 'zh',
                'code_tmx': 'zh-MO',
                'code_639_3': 'zho',
                'name': 'Chinese (traditional, Macao SAR)'
            },
    }

    for key, value in langlist.items():
        plural_forms = ""
        for i in all_curr_languages:
            if i.code == value['code']:
                plural_forms = i.plural_forms
        new_lang = Language(
            name=value['name'],
            code=value['code'],
            code_639_3=value['code_639_3'],
            code_tmx=value['code_tmx'],
            code_region=key,
            plural_forms=plural_forms
        )
        new_lang.save()


class Migration(migrations.Migration):
    dependencies = [
        ('entries', '0005_language_code_tmx'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code_region',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.RunPython(add_regional_languages),
    ]
