# Generated by Django 2.2 on 2022-07-22 13:09

from unicodedata import name
from django.db import migrations

def add_turkish_language(apps, schema_editor):
    Language = apps.get_model('entries', 'Language')
    turkish = Language(
        name="Turkish",
        code = "tr",
        code_639_3 = "tur",
        code_tmx = "tr-TR",
        code_region = "tr_TR",
        plural_forms = "nplurals=2; plural=(n > 1);"
    )
    turkish_cyprus = Language(
        name="Turkish (Cyprus)",
        code = "tr",
        code_639_3 = "tur",
        code_tmx = "tr-CY",
        code_region = "tr_CY",
        plural_forms = "nplurals=2; plural=(n > 1);"
    )
    turkish.save()
    turkish_cyprus.save()

class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_language_code_region'),
    ]

    operations = [
        migrations.RunPython(add_turkish_language),
    ]
