# Generated by Django 2.2 on 2026-07-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0044_auto_20260709_2040'),
        ('entries', '0007_turkish_lang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
