# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-18 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def project_set_source_lang_and_create_translation(apps, schema_editor):
    Project = apps.get_model('translations', 'Project')
    ProjectTranslation = apps.get_model('translations', 'ProjectTranslation')
    Text = apps.get_model('translations', 'Text')
    TextTranslations = apps.get_model('translations', 'TextTranslation')
    Language = apps.get_model('entries', 'Language')

    all_projects = Project.objects.all()
    for proj in all_projects:
        proj_texts = Text.objects.filter(project=proj)
        if len(proj_texts) > 0:
            source_lang = proj_texts[0].source_lang
            txt_trans = TextTranslations.objects.get(text=proj_texts[0])
            target_lang = txt_trans.target_lang
        else:
            source_lang = Language.objects.get(code='en')
            target_lang = Language.objects.get(code='ru')
        proj.source_lang = source_lang
        proj.save()
        new_proj_trans = ProjectTranslation(
            project=proj,
            target_lang=target_lang,
        )
        new_proj_trans.save()
        new_proj_trans.glossaries_list.add(*proj.glossaries_list.all())
        new_proj_trans.tmdatabases_list.add(*proj.tmdatabases_list.all())
        for text in proj_texts:
            text_trans = TextTranslations.objects.get(text=text)
            text_trans.project_translation = new_proj_trans
            text_trans.save()

class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_language_plural_forms'),
        ('translations', '0024_auto_20170313_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glossaries_list', models.ManyToManyField(to='translations.Glossary')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='source_lang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_source_lang', to='entries.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_translations', to='translations.Project'),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='target_lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_translations_target_lang', to='entries.Language'),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='tmdatabases_list',
            field=models.ManyToManyField(to='translations.TMDatabase'),
        ),
        migrations.AddField(
            model_name='texttranslation',
            name='project_translation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_translation_relation', to='translations.ProjectTranslation'),
            preserve_default=False,
        ),
        migrations.RunPython(project_set_source_lang_and_create_translation),
    ]
