# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-27 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def copy_members_from_project_text_field_to_new_model(apps, schema_editor):
    Project = apps.get_model('translations', 'Project')
    ProjectMember = apps.get_model('translations', 'ProjectMember')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    all_projects = Project.objects.all()
    for proj in all_projects:
        members_list = proj.members.split(',') if proj.members else []
        if members_list:
            users_list = User.objects.filter(id__in=members_list)
            for user in users_list:
                new_project_member = ProjectMember(project=proj,
                                                   user=user,
                                                   )
                new_project_member.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0025_auto_20171018_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, b'Manager'), (1, b'Translator'), (2, b'Spectator')], default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='translations.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(copy_members_from_project_text_field_to_new_model),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='project_members', through='translations.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
