# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0026_auto_20180127_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_invited',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_requested',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='status',
            field=models.IntegerField(choices=[(0, 'Editor'), (1, 'Translator'), (2, 'Spectator')], default=1),
        ),
        migrations.AlterField(
            model_name='text',
            name='options',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='voters',
            field=models.TextField(default=''),
        ),
    ]
