# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tolmach', '0011_auto_20180330_1906'),
        ('translations', '0027_auto_20180308_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_organization', to='tolmach.Organization'),
        ),
    ]
