# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 08:24
from __future__ import unicode_literals

from django.db import migrations, models
from tolmach.utils import random_string

def update_invite_link_codes(apps, schema_editor):
    Project = apps.get_model('translations', 'Project')

    all_projs = Project.objects.all()

    for pr in all_projs:
        pr.invite_link_code = random_string(15)
        pr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0028_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invite_link_code',
            field=models.CharField(default=None, null=True, unique=True, max_length=15),
        ),
        migrations.RunPython(update_invite_link_codes),
    ]
