# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import translations.models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0029_project_invite_link_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='invite_link_code',
            field=models.CharField(default=translations.models.random_invite_code, max_length=15, null=True, unique=True),
        ),
    ]
