# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models

def move_entry_meta_from_separate_table(apps, schema_editor):
    TextEntry = apps.get_model('translations', 'TextEntry')
    TextEntryMeta = apps.get_model('translations', 'TextEntryMeta')

    all_entry_metas = TextEntryMeta.objects.all()

    for mt in all_entry_metas:
        entry = mt.entry
        entry.meta_data = mt.meta_data
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0030_auto_20180424_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='meta_data',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(move_entry_meta_from_separate_table),
    ]
