# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-10 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0031_textentry_meta_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textentrymeta',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='textentrymeta',
            name='text_meta',
        ),
        migrations.DeleteModel(
            name='TextEntryMeta',
        ),
    ]
