# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-16 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0032_auto_20181010_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTranslationUserPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=0)),
                ('fragment', models.IntegerField(default=0)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_translation_user_position', to='translations.TextTranslation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='texttranslationuserposition',
            unique_together=set([('translation', 'user')]),
        ),
    ]
