# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-08 15:27
from __future__ import unicode_literals

from django.db import migrations, models

# def get_text_translation_progress(text_translation):
#     from translations.models import TextEntry
#
#     # self = text_translation
#     entries_total = TextEntry.objects.filter(text=text_translation.text, parent_entry=None).count()
#     entries_translated = TextEntry.objects.filter(~Q(parent_entry=None), text=text_translation.text, translation=text_translation).values(
#         'parent_entry').distinct().count()
#     entries_approved = TextEntry.objects.filter(text=text_translation.text, translation=text_translation, is_approved=True).count()
#
#     if not entries_total == 0:
#         percent_translated = int(math.ceil(entries_translated / (entries_total / 100.0))) if (
#                     entries_translated < entries_total) else 100
#         percent_approved = int(math.ceil(entries_approved / (entries_total / 100.0)))
#
#         return [int(entries_total), int(entries_translated), int(entries_approved)], [percent_translated,
#                                                                                       percent_approved]
#     else:
#         return [int(entries_total), int(entries_translated), int(entries_approved)], [0, 0]

# def generate_initial_projects_progress(apps, schema_editor):
#     from tolmach import tasks
#
#     tasks.update_projects_progress(full_update='true')
    # Project = apps.get_model('translations', 'Project')
    # Text = apps.get_model('translations', 'Text')
    # TextTranslation = apps.get_model('translations', 'TextTranslation')
    #
    # results = Project.objects.all()
    #
    # for project in results:
    #     translated_progress = 0
    #     approved_progress = 0
    #     translations_num = 0
    #     texts = Text.objects.filter(project=project)
    #     for text in texts:
    #         translations = TextTranslation.objects.filter(text=text)
    #         for translation in translations:
    #             translations_num += 1
    #             translated_progress += get_text_translation_progress(translation)[1][0]
    #             approved_progress += get_text_translation_progress(translation)[1][1]
    #
    #     if not texts.count() == 0:
    #         project_progress = [int(approved_progress / translations_num),
    #                             int(translated_progress / translations_num) - int(approved_progress / translations_num)]
    #     else:
    #         project_progress = [0, 0]
    #
    #     project.progress_data = json.dumps(project_progress)
    #     project.save()



class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0033_auto_20181116_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_data',
            field=models.CharField(default='[0, 0]', max_length=15),
        ),
        # migrations.RunPython(generate_initial_projects_progress),
    ]
