# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0034_project_progress_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
