# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0035_textentry_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdatabaseentry',
            name='orig_lang',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tmdatabaseentry',
            name='target_lang',
            field=models.CharField(max_length=5),
        ),
    ]
