# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-23 11:18
from __future__ import unicode_literals

from django.db import migrations, models

def get_entries_newlines_from_text_bodies(apps, schema_editor):

    Text = apps.get_model('translations', 'Text')
    TextEntry = apps.get_model('translations', 'TextEntry')

    for text in Text.objects.all():
        base_entries = TextEntry.objects.filter(text=text, parent_entry=None)
        text_body = text.body

        search_start = 0
        for entry in base_entries:
            entry_to_body = '<span data-entry="%d">%s</span>' % (entry.id_in_text, entry.body)
            # ищем позицию в прегенерённом тексте
            pos_start = text_body.find(entry_to_body, search_start)
            pos_stop = pos_start + len(entry_to_body)
            search_start = pos_stop
            # ищем, есть ли переносы и если есть, то сколько
            new_lines = 0
            cur_char = ""
            cur_char_num = 0
            while not cur_char == "<" and pos_stop + cur_char_num < len(text_body):
                cur_char = text_body[pos_stop + cur_char_num]
                if cur_char == '\n':
                    new_lines += 1
                cur_char_num +=1

            if new_lines > 0:
                entry.new_lines_after = new_lines
                entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0036_auto_20190320_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='new_lines_after',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(get_entries_newlines_from_text_bodies),
    ]
