# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import translations.models
from tolmach.utils import random_string

def update_fragment_preview_codes(apps, schema_editor):
    TextEntry = apps.get_model('translations', 'TextEntry')

    all_entries = TextEntry.objects.all()

    for ent in all_entries:
        ent.preview_code = random_string(10)
        ent.save()

class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0037_textentry_new_lines_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='preview_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='textentry',
            unique_together=set([('preview_code', 'text')]),
        ),
        migrations.RunPython(update_fragment_preview_codes),
    ]
