# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-07 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import translations.models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0038_auto_20190504_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='meta_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='preview_code',
            field=models.CharField(default=translations.models.random_fragment_preview_code, max_length=10, null=True),
        ),
    ]
