# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.db.models import Q
from translations.utils import unescape_html

def migrate_plain_text_preexport_entries(apps, schema_editor):

    Text = apps.get_model('translations', 'Text')
    TextTranslation = apps.get_model('translations', 'TextTranslation')
    TextEntry = apps.get_model('translations', 'TextEntry')
    PreexportEntry = apps.get_model('translations', 'PreexportEntry')

    # выбираем все утверждённые фрагменты в текстах plain text
    approved_entries = TextEntry.objects.filter(text__document_format = "text/plain", is_approved = True).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified')
    print("approved_entries", TextEntry.objects.filter(text__document_format = "text/plain", is_approved = True).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified').count())

    # собираем список айдишников родителей утверждённых фрагментов
    approved_parent_ids = [x.parent_entry.id for x in approved_entries]

    # выбираем все остальные, не утверждённые переводы фрагментов из текстов plain text, исключаем список утверждённых
    all_other_entries = TextEntry.objects.filter(~Q(parent_entry=None), text__document_format = "text/plain").exclude(parent_entry_id__in=approved_parent_ids).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified').iterator()
    print("all_other_entries", TextEntry.objects.filter(~Q(parent_entry=None), text__document_format = "text/plain").exclude(parent_entry_id__in=approved_parent_ids).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified').count())

    # собираем список айдишников родителей неутверждённх переводов
    all_other_entries_parent_ids = [x.parent_entry.id for x in all_other_entries]

    # выбираем все родители без переводов
    all_not_translated_entries = TextEntry.objects.filter(parent_entry=None, text__document_format = "text/plain").exclude(id__in=approved_parent_ids+ all_other_entries_parent_ids).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified').iterator()
    print("all_not_translated_entries", TextEntry.objects.filter(parent_entry=None, text__document_format = "text/plain").exclude(id__in=approved_parent_ids + all_other_entries_parent_ids).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified').count())

    from itertools import chain

    all_len = TextEntry.objects.filter(text__document_format = "text/plain", is_approved = True).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified').count() + \
              TextEntry.objects.filter(~Q(parent_entry=None), text__document_format = "text/plain").exclude(parent_entry_id__in=approved_parent_ids).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified').count() + \
              TextEntry.objects.filter(parent_entry=None, text__document_format = "text/plain").exclude(id__in=approved_parent_ids + all_other_entries_parent_ids).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified').count()

    n = 1

    max_bulk = 500
    curr_bulk = 0
    bulk_list = []

    for entry in chain(TextEntry.objects.filter(text__document_format = "text/plain", is_approved = True).defer('author', 'meta_data', 'preview_code', 'vote', 'voters', 'is_disabled', 'time_created', 'last_modified').iterator(),
                       TextEntry.objects.filter(~Q(parent_entry=None), text__document_format="text/plain").exclude(
                           parent_entry_id__in=approved_parent_ids).defer('author', 'meta_data', 'preview_code', 'vote', 'voters',
                                                      'is_disabled', 'time_created', 'last_modified').iterator(),
                       all_not_translated_entries):
        if entry.parent_entry == None:
            translations = TextTranslation.objects.filter(text=entry.text)
            new_objects_list = []
            for i in translations:
                body_ending = "\n" * entry.new_lines_after if entry.new_lines_after > 0 else " "
                new_body = unescape_html(entry.body) + body_ending
                new_objects_list.append({
                    "new_parent": entry,
                    "new_id_in_text": entry.id_in_text,
                    "new_body": new_body,
                    "translation": i,
                    "entry": entry
                })
        else:
            body_ending = "\n" * entry.parent_entry.new_lines_after if entry.parent_entry.new_lines_after > 0 else " "
            if entry.is_approved:
                new_body = unescape_html(entry.body) + body_ending
            else:
                new_body = unescape_html(entry.parent_entry.body) + body_ending
            new_objects_list = [
                {
                    "new_parent": entry.parent_entry,
                    "new_id_in_text": entry.parent_entry.id_in_text,
                    "new_body": new_body,
                    "translation": entry.translation,
                    "entry": entry
                }
            ]

        for i in new_objects_list:
            object = PreexportEntry(parent_entry=i["new_parent"],
                                   text=i["entry"].text,
                                   translation=i["translation"])

            object.body = i["new_body"]
            object.id_in_text = i["new_id_in_text"]
            # object.save()
            if curr_bulk < max_bulk:
                curr_bulk += 1
                print(f"{n} / {all_len}", object.body)
                bulk_list.append(object)
            else:
                PreexportEntry.objects.bulk_create(bulk_list)
                bulk_list = []
                curr_bulk = 0
        n += 1
    PreexportEntry.objects.bulk_create(bulk_list)

class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0039_auto_20190607_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreexportEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('id_in_text', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_entry', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.TextEntry')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_preexport_entries', to='translations.Text')),
                ('translation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_preexport_entries', to='translations.TextTranslation')),
            ],
        ),
        migrations.RunPython(migrate_plain_text_preexport_entries),
    ]
