# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-17 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import translations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0040_preexportentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTextEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('id_in_text', models.IntegerField(default=0)),
                ('new_lines_after', models.IntegerField(default=0)),
                ('meta_data', models.TextField(default='{}')),
                ('preview_code', models.CharField(default=translations.models.random_fragment_preview_code, max_length=10, null=True)),
                ('vote', models.IntegerField(default=0)),
                ('voters', models.TextField(default='')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_entry', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='translations.TextEntry')),
                ('text', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='translations.Text')),
                ('translation', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='translations.TextTranslation')),
            ],
            options={
                'verbose_name': 'historical text entry',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='preexportentry',
            unique_together=set([('parent_entry', 'translation')]),
        ),
    ]
