# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-25 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0041_auto_20191117_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Ready'), (2, 'Deleted')], default=1),
        ),
        migrations.AddField(
            model_name='text',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Ready'), (2, 'Deleted')], default=1),
        ),
    ]
