# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0042_auto_20200425_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='glossaries_list',
            field=models.ManyToManyField(blank=True, to='translations.Glossary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tmdatabases_list',
            field=models.ManyToManyField(blank=True, to='translations.TMDatabase'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_invited',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_requested',
            field=models.TextField(blank=True, default=''),
        ),
    ]
