# Generated by Django 2.2 on 2026-07-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0044_auto_20260318_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltextentry',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical text entry', 'verbose_name_plural': 'historical text entrys'},
        ),
        migrations.RemoveField(
            model_name='text',
            name='subject',
        ),
        migrations.AlterField(
            model_name='historicaltextentry',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
